- name: Configure Local Development Environment
  hosts: localhost
  connection: local

  tasks:
    - name: Install Python
      become: yes
      apt:
        name: python3
        state: present

    - name: Create project directory
      file:
        path: /mnt/c/devops-midterm/project
        state: directory
        mode: '0755'

    - name: Copy application files
      copy:
        src: /mnt/c/devops-midterm/app/
        dest: /mnt/c/devops-midterm/project/app/
        mode: '0644'